update_fastlane

default_platform(:ios)

platform :ios do

  desc "General build routine"
  lane :custom_lane do

    #ensure_git_status_clean

    clear_derived_data

    xcclean(
      workspace: "GBShop.xcworkspace",
      scheme: "GBShop"
    )

    cocoapods(
      use_bundle_exec: false
    )

    run_tests

  end
end
